spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ws-clietn-info
          uri: lb://eureka-client-ws
          predicates:
            - Path=/ws/info/**
        - id: ws-client
          uri: lb:ws://eureka-client-ws
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1
        - id: client
          uri: lb://eureka-consumer
          predicates:
            - Path=/c/**
          filters:
            - StripPrefix=1


server:
  port: 1101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
